In [1]:
import torch

#### Setence taken `Your journey starts with one step` 

In [2]:
inputs = torch.tensor([
    [ 0.43, 0.15,  0.89],
    [0.55,  0.87,  0.66],
    [ 0.57,  0.85, 0.64],
    [0.22, 0.58,  0.33],
    [ 0.77,  0.25, 0.10],
    [ 0.05,  0.80,  0.55]
], dtype=torch.float32)


In [3]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [4]:
query = inputs[1]  # Second 

attn_scores_2=torch.empty(inputs.shape[0])

In [5]:
for i,x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(query, x_i)

In [6]:
for i,x_i in enumerate(inputs):
    print("query:",query,'x_i',x_i)


torch.dot(query,inputs[1])

query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.4300, 0.1500, 0.8900])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.5500, 0.8700, 0.6600])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.5700, 0.8500, 0.6400])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.2200, 0.5800, 0.3300])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.7700, 0.2500, 0.1000])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.0500, 0.8000, 0.5500])


tensor(1.4950)

In [7]:
attn_scores_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [8]:
normalized_attn_scores_2 = attn_scores_2 / attn_scores_2.sum()


print(attn_scores_2)
print(normalized_attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])


### Softmax Implementation for Attention Scores

In [9]:
def naive_softmax(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

In [10]:
attn_scores_2_native_softmax = naive_softmax(attn_scores_2)

print(attn_scores_2_native_softmax)
print(attn_scores_2_native_softmax.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [11]:
attn_scores_2_softmax_torch = torch.softmax(attn_scores_2, dim=0)

print(attn_scores_2_softmax_torch)
print(attn_scores_2_softmax_torch.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [12]:
context_vector_2 = torch.zeros(query.shape)

for i,x_i in enumerate(inputs):
    context_vector_2 += attn_scores_2_softmax_torch[i] * x_i

print(context_vector_2)

tensor([0.4419, 0.6515, 0.5683])


In [13]:
attn_scores=torch.empty(6,6)

In [14]:
attn_scores = inputs @ inputs.T

In [15]:
inputs[0]

tensor([0.4300, 0.1500, 0.8900])

In [16]:
attn_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [17]:
attn_weights=torch.softmax(attn_scores,dim=-1)
attn_weights

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [18]:
attn_weights[:,2]

tensor([0.1981, 0.2333, 0.2326, 0.2046, 0.1975, 0.2128])

In [19]:
context_matrix=attn_weights @ inputs

In [20]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [21]:
context_matrix

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

In [22]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

## Self Attention With Traianble Weights

In [23]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [24]:
x_2=inputs[1]
d_in=inputs.shape[1]
d_out=2

In [25]:
torch.manual_seed(123)
W_query=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_key=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_value=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)

In [26]:
W_value

Parameter containing:
tensor([[0.0756, 0.1966],
        [0.3164, 0.4017],
        [0.1186, 0.8274]])

In [27]:
query=inputs@W_query
key=inputs@W_key
value=inputs@W_value

In [28]:
query

tensor([[0.2309, 1.0966],
        [0.4306, 1.4551],
        [0.4300, 1.4343],
        [0.2355, 0.7990],
        [0.2983, 0.6565],
        [0.2568, 1.0533]])

In [29]:
QK=query@key.T

In [30]:
QK

tensor([[0.9231, 1.3545, 1.3241, 0.7910, 0.4032, 1.1330],
        [1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440],
        [1.2544, 1.8284, 1.7877, 1.0654, 0.5508, 1.5238],
        [0.6973, 1.0167, 0.9941, 0.5925, 0.3061, 0.8475],
        [0.6114, 0.8819, 0.8626, 0.5121, 0.2707, 0.7307],
        [0.8995, 1.3165, 1.2871, 0.7682, 0.3937, 1.0996]])

In [31]:
d_k=key.shape[-1]
attn_weights_2=torch.softmax(QK/d_k**0.5,dim=-1)

In [32]:
V=inputs@W_value

In [33]:
final_attn_weights=attn_weights@V

In [34]:
final_attn_weights

tensor([[0.2897, 0.8043],
        [0.3069, 0.8188],
        [0.3063, 0.8173],
        [0.2972, 0.7936],
        [0.2848, 0.7650],
        [0.3043, 0.8105]])

In [35]:
import torch
import torch.nn as nn

class SelfAttention_v1(nn.Module):
    """
    A single-head self-attention mechanism.

    This module projects the input into query, key, and value vectors
    and then computes the attention weights and context vectors.
    """
    def __init__(self, d_in: int, d_out: int):
        """
        Initializes the SelfAttention_v1 module.

        Args:
            d_in (int): The dimensionality of the input feature vector.
            d_out (int): The dimensionality of the output query, key, and value vectors.
        """
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=False)
        self.W_key = nn.Linear(d_in, d_out, bias=False)
        self.W_value = nn.Linear(d_in, d_out, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Performs the forward pass of the self-attention mechanism.

        Args:
            x (torch.Tensor): The input tensor of shape (batch_size, num_tokens, d_in).

        Returns:
            torch.Tensor: The context vector of shape (batch_size, num_tokens, d_out).
        """
        # Project inputs into query, key, and value vectors
        queries = self.W_query(x)
        keys = self.W_key(x)
        values = self.W_value(x)

        # Compute attention scores
        # The last dimension of keys is d_out, so we transpose the last two dimensions
        attn_scores = queries @ keys.T

        # Scale scores and apply softmax to get weights
        # The scaling factor is the square root of the key dimension
        attn_weights = torch.softmax(attn_scores / self.d_out**0.5, dim=-1)

        # Compute the context vectors by weighting the values
        context_vec = attn_weights @ values
        return context_vec

In [36]:
torch.manual_seed(200)
attention_v1=SelfAttention_v1(d_in,d_out)

In [37]:
atten_weights_3=attention_v1(inputs)

## Causal Attention

In [38]:
context_length=atten_weights_3.shape[0]

In [39]:
mask_simple=torch.tril(torch.ones(context_length,context_length))

In [40]:
mask_simple

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])

In [41]:
masked_attn=attn_weights_2*mask_simple

In [42]:
masked_attn

tensor([[0.1551, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1500, 0.2264, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1503, 0.2256, 0.2192, 0.0000, 0.0000, 0.0000],
        [0.1591, 0.1994, 0.1962, 0.1477, 0.0000, 0.0000],
        [0.1610, 0.1949, 0.1923, 0.1501, 0.1265, 0.0000],
        [0.1557, 0.2092, 0.2048, 0.1419, 0.1089, 0.1794]])

In [43]:
rows_sums = masked_attn.sum(dim=1,keepdim=True)
masked_simple_norm=masked_attn/rows_sums

In [44]:
masked_simple_norm

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3986, 0.6014, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2526, 0.3791, 0.3683, 0.0000, 0.0000, 0.0000],
        [0.2265, 0.2839, 0.2794, 0.2103, 0.0000, 0.0000],
        [0.1952, 0.2363, 0.2331, 0.1820, 0.1534, 0.0000],
        [0.1557, 0.2092, 0.2048, 0.1419, 0.1089, 0.1794]])

In [45]:
masked_attn.sum(dim=1,keepdim=True)

tensor([[0.1551],
        [0.3764],
        [0.5952],
        [0.7024],
        [0.8248],
        [1.0000]])

In [46]:
masked_attn

tensor([[0.1551, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1500, 0.2264, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1503, 0.2256, 0.2192, 0.0000, 0.0000, 0.0000],
        [0.1591, 0.1994, 0.1962, 0.1477, 0.0000, 0.0000],
        [0.1610, 0.1949, 0.1923, 0.1501, 0.1265, 0.0000],
        [0.1557, 0.2092, 0.2048, 0.1419, 0.1089, 0.1794]])

#### The above ones are not efficient so now will do the efficient way cause after doing softmax it creates an data leakage

In [47]:
attn_weights_2

tensor([[0.1551, 0.2104, 0.2059, 0.1413, 0.1074, 0.1799],
        [0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820],
        [0.1503, 0.2256, 0.2192, 0.1315, 0.0914, 0.1819],
        [0.1591, 0.1994, 0.1962, 0.1477, 0.1206, 0.1769],
        [0.1610, 0.1949, 0.1923, 0.1501, 0.1265, 0.1752],
        [0.1557, 0.2092, 0.2048, 0.1419, 0.1089, 0.1794]])

In [48]:
mask=torch.triu(torch.ones(context_length,context_length),diagonal=1)
masked=attn_weights_2.masked_fill(mask.bool(),-torch.inf)
masked

tensor([[0.1551,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.1500, 0.2264,   -inf,   -inf,   -inf,   -inf],
        [0.1503, 0.2256, 0.2192,   -inf,   -inf,   -inf],
        [0.1591, 0.1994, 0.1962, 0.1477,   -inf,   -inf],
        [0.1610, 0.1949, 0.1923, 0.1501, 0.1265,   -inf],
        [0.1557, 0.2092, 0.2048, 0.1419, 0.1089, 0.1794]])

In [49]:
atten_weights_4=torch.softmax(masked/key.shape[-1]**0.5,dim=1)
atten_weights_4

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4865, 0.5135, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3221, 0.3397, 0.3382, 0.0000, 0.0000, 0.0000],
        [0.2471, 0.2542, 0.2536, 0.2451, 0.0000, 0.0000],
        [0.1994, 0.2042, 0.2039, 0.1979, 0.1946, 0.0000],
        [0.1653, 0.1717, 0.1712, 0.1637, 0.1599, 0.1681]])

## Dropout

In [50]:
torch.manual_seed(200)
dropout=torch.nn.Dropout(0.5)


## Demo Example How Dropout Work
print(dropout(torch.ones(6,6)))

tensor([[0., 0., 0., 0., 0., 2.],
        [2., 2., 0., 0., 2., 0.],
        [0., 0., 2., 0., 0., 0.],
        [2., 0., 2., 2., 0., 2.],
        [2., 0., 0., 0., 0., 2.],
        [2., 0., 2., 2., 2., 2.]])


In [51]:
torch.manual_seed(200)

print(dropout(atten_weights_4))


tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.9730, 1.0270, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.6764, 0.0000, 0.0000, 0.0000],
        [0.4941, 0.0000, 0.5073, 0.4902, 0.0000, 0.0000],
        [0.3988, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3307, 0.0000, 0.3423, 0.3275, 0.3199, 0.3362]])


## Step,Operation,"The Logical ""Why"""
1. Q⋅KT,Calculate raw similarity scores.
2. Scale (d​1​),Normalize the scores so gradients don't vanish.
3. Mask,"Apply the ""don't look ahead"" rule."
4. Softmax,Convert scores to probabilities (0.0 to 1.0).
5. Dropout,Randomly break connections to improve learning.
6. ⋅V,Mix the content based on the probabilities.

In [52]:
class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout)
        
        self.register_buffer(
            'mask',
            torch.triu(torch.ones(context_length, context_length), diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        # 1. Compute Raw Scores
        attn_scores = queries @ keys.transpose(1, 2)

        # 2. SCALE FIRST (The Correction)
        # We scale the dot products down before masking.
        # This prevents large numbers from exploding and ensures numerical stability.
        attn_scores = attn_scores / self.d_out**0.5
        
        # 3. MASK SECOND (The Correction)
        # We apply the mask to the already-scaled scores.
        # This guarantees the mask value (even if finite) isn't accidentally shrunk.
        attn_scores.masked_fill_(
            self.mask[:num_tokens, :num_tokens].bool(), -torch.inf
        )

        # 4. Softmax
        # Note: We removed the division here because we did it in Step 2.
        attn_weights = torch.softmax(attn_scores, dim=-1)
        
        # 5. Dropout
        attn_weights = self.dropout(attn_weights)

        context_vec = attn_weights @ values
        return context_vec

In [53]:
batch=torch.stack((inputs,inputs),dim=0)

In [54]:
context_length=batch.shape[1]

causal_attn_obj=CausalAttention(d_in=d_in,d_out=d_out, context_length=context_length, dropout=0.3)

In [55]:
causal_attn_weights=causal_attn_obj(batch)

In [56]:
causal_attn_weights

tensor([[[ 0.0000,  0.0000],
         [ 0.0983,  0.3780],
         [-0.1334,  0.0204],
         [-0.0083,  0.3134],
         [ 0.0242,  0.3473],
         [ 0.0187,  0.2463]],

        [[ 0.0000,  0.0000],
         [-0.1039,  0.4090],
         [-0.0680,  0.2686],
         [ 0.0935,  0.2976],
         [ 0.0261,  0.4011],
         [ 0.1180,  0.3631]]], grad_fn=<UnsafeViewBackward0>)

## **Multi Head Attention**

In [57]:
class MultiHeadAttentionWrapper(nn.Module):

    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        self.heads=nn.ModuleList(
            [CausalAttention(d_in=d_in,d_out=d_out,context_length=context_length,dropout=dropout,qkv_bias=qkv_bias)
              for _ in range(num_heads)]
        )
    def forward(self,x):
        return torch.cat([head(x) for head in self.heads],dim=-1)

In [58]:
torch.manual_seed(123)
context_length=batch.shape[1]
d_in,d_out=3,2
MHA=MultiHeadAttentionWrapper(d_in,d_out,context_length,0.0,num_heads=3)
context_vecs=MHA(batch)

In [59]:
context_vecs

tensor([[[-0.4519,  0.2216,  0.4772,  0.1063,  0.4566,  0.2729],
         [-0.5874,  0.0058,  0.5891,  0.3257,  0.5792,  0.3011],
         [-0.6300, -0.0632,  0.6202,  0.3860,  0.6249,  0.3102],
         [-0.5675, -0.0843,  0.5478,  0.3589,  0.5691,  0.2785],
         [-0.5526, -0.0981,  0.5321,  0.3428,  0.5543,  0.2520],
         [-0.5299, -0.1081,  0.5077,  0.3493,  0.5337,  0.2499]],

        [[-0.4519,  0.2216,  0.4772,  0.1063,  0.4566,  0.2729],
         [-0.5874,  0.0058,  0.5891,  0.3257,  0.5792,  0.3011],
         [-0.6300, -0.0632,  0.6202,  0.3860,  0.6249,  0.3102],
         [-0.5675, -0.0843,  0.5478,  0.3589,  0.5691,  0.2785],
         [-0.5526, -0.0981,  0.5321,  0.3428,  0.5543,  0.2520],
         [-0.5299, -0.1081,  0.5077,  0.3493,  0.5337,  0.2499]]],
       grad_fn=<CatBackward0>)

In [60]:
context_vecs.shape

torch.Size([2, 6, 6])

#### **IMPLEMENTING MULTIHEAD ATTENTION WITH WEIGHT SPLITS**

In [71]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        assert (d_out % num_heads == 0), \
            "d_out must be divisible by num_heads"

        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads # Reduce the projection dim to match desired output dim

        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.out_proj = nn.Linear(d_out, d_out)  # Linear layer to combine head outputs
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            "mask",
            torch.triu(torch.ones(context_length, context_length),
                       diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape

        keys = self.W_key(x) # Shape: (b, num_tokens, d_out)
        queries = self.W_query(x)
        values = self.W_value(x)

        # We implicitly split the matrix by adding a `num_heads` dimension
        # Unroll last dim: (b, num_tokens, d_out) -> (b, num_tokens, num_heads, head_dim)
        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim) 
        values = values.view(b, num_tokens, self.num_heads, self.head_dim)
        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)

        # Transpose: (b, num_tokens, num_heads, head_dim) -> (b, num_heads, num_tokens, head_dim)
        keys = keys.transpose(1, 2)
        queries = queries.transpose(1, 2)
        values = values.transpose(1, 2)

        # Compute scaled dot-product attention (aka self-attention) with a causal mask
        attn_scores = queries @ keys.transpose(2, 3)  # Dot product for each head

        # Original mask truncated to the number of tokens and converted to boolean
        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]

        # Use the mask to fill attention scores
        attn_scores.masked_fill_(mask_bool, -torch.inf)
        
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)

        # Shape: (b, num_tokens, num_heads, head_dim)
        context_vec = (attn_weights @ values).transpose(1, 2) 
        
        # Combine heads, where self.d_out = self.num_heads * self.head_dim
        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)
        context_vec = self.out_proj(context_vec) # optional projection

        return context_vec

In [75]:
torch.manual_seed(123)

# Define the tensor with 3 rows and 6 columns
inputs = torch.tensor(
    [[0.43, 0.15, 0.89, 0.55, 0.87, 0.66],  # Row 1
     [0.57, 0.85, 0.64, 0.22, 0.58, 0.33],  # Row 2
     [0.77, 0.25, 0.10, 0.05, 0.80, 0.55]]  # Row 3
)

batch = torch.stack((inputs, inputs), dim=0)
print(batch.shape) 

batch_size, context_length, d_in = batch.shape
d_out = 6
mha = MultiHeadAttention(d_in, d_out, context_length, 0.0, num_heads=2)
context_vecs = mha(batch)
print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

torch.Size([2, 3, 6])
tensor([[[ 0.1569, -0.0873,  0.0210,  0.0215, -0.3243, -0.2518],
         [ 0.1117, -0.0547,  0.0406, -0.0213, -0.3251, -0.2993],
         [ 0.1196, -0.0491,  0.0318, -0.0635, -0.2788, -0.2578]],

        [[ 0.1569, -0.0873,  0.0210,  0.0215, -0.3243, -0.2518],
         [ 0.1117, -0.0547,  0.0406, -0.0213, -0.3251, -0.2993],
         [ 0.1196, -0.0491,  0.0318, -0.0635, -0.2788, -0.2578]]],
       grad_fn=<ViewBackward0>)
context_vecs.shape: torch.Size([2, 3, 6])


## Actual Production Scenario

In [76]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class MultiHeadAttentionProd(nn.Module):
    def __init__(self, d_model=768, n_head=12):
        super().__init__()
        self.n_head = n_head
        self.d_model = d_model
        self.head_dim = d_model // n_head
        
        # Ensure the dimensions are divisible
        assert d_model % n_head == 0, "Embedding length must be divisible by number of heads"

        # 1. The Projections (Linear layers)
        # We create the Query, Key, and Value matrices
        self.w_q = nn.Linear(d_model, d_model)
        self.w_k = nn.Linear(d_model, d_model)
        self.w_v = nn.Linear(d_model, d_model)
        
        # The final output layer after merging heads
        self.fc_out = nn.Linear(d_model, d_model)

    def forward(self, x):
        # x shape: [Batch_Size, Seq_Len, 768]
        batch_size, seq_len, _ = x.shape
        
        # STEP 1: Linear Transformation
        # Pass input through Q, K, V weights
        Q = self.w_q(x)  # [Batch, Seq_Len, 768]
        K = self.w_k(x)  # [Batch, Seq_Len, 768]
        V = self.w_v(x)  # [Batch, Seq_Len, 768]

        # STEP 2: Splitting into 12 Heads
        # Reshape to [Batch, Seq_Len, 12, 64] then swap dimensions (Transpose)
        # Final shape: [Batch, 12, Seq_Len, 64]
        Q = Q.view(batch_size, seq_len, self.n_head, self.head_dim).transpose(1, 2)
        K = K.view(batch_size, seq_len, self.n_head, self.head_dim).transpose(1, 2)
        V = V.view(batch_size, seq_len, self.n_head, self.head_dim).transpose(1, 2)

        # STEP 3: Scaled Dot-Product Attention
        # Calculate scores by multiplying Q and K
        # Energy shape: [Batch, 12, Seq_Len, Seq_Len]
        energy = torch.matmul(Q, K.transpose(-2, -1)) / (self.head_dim ** 0.5)
        
        # Apply Softmax to get attention weights (probabilities)
        attention = torch.softmax(energy, dim=-1)

        # STEP 4: Apply Attention to Values
        # Out shape: [Batch, 12, Seq_Len, 64]
        out = torch.matmul(attention, V)

        # STEP 5: Merge (Concatenate) Heads
        # Transpose back and reshape to [Batch, Seq_Len, 768]
        out = out.transpose(1, 2).contiguous().view(batch_size, seq_len, self.d_model)

        # STEP 6: Final Linear Projection
        return self.fc_out(out)

In [79]:
torch.manual_seed(123)

batch_size, context_length, d_in = batch.shape
d_out = 6
mha = MultiHeadAttentionProd(d_model=d_in, n_head=2)
context_vecs = mha(batch)
print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tensor([[[-0.3464,  0.3428,  0.3846, -0.1505,  0.1512,  0.0491],
         [-0.3462,  0.3426,  0.3844, -0.1505,  0.1516,  0.0493],
         [-0.3465,  0.3427,  0.3842, -0.1503,  0.1512,  0.0489]],

        [[-0.3464,  0.3428,  0.3846, -0.1505,  0.1512,  0.0491],
         [-0.3462,  0.3426,  0.3844, -0.1505,  0.1516,  0.0493],
         [-0.3465,  0.3427,  0.3842, -0.1503,  0.1512,  0.0489]]],
       grad_fn=<ViewBackward0>)
context_vecs.shape: torch.Size([2, 3, 6])
