In [1]:
import torch

#### Setence taken `Your journey starts with one step` 

In [2]:
inputs = torch.tensor([
    [ 0.43, 0.15,  0.89],
    [0.55,  0.87,  0.66],
    [ 0.57,  0.85, 0.64],
    [0.22, 0.58,  0.33],
    [ 0.77,  0.25, 0.10],
    [ 0.05,  0.80,  0.55]
], dtype=torch.float32)


In [3]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [4]:
query = inputs[1]  # Second 

attn_scores_2=torch.empty(inputs.shape[0])

In [5]:
for i,x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(query, x_i)

In [47]:
for i,x_i in enumerate(inputs):
    print("query:",query,'x_i',x_i)


torch.dot(query,inputs[1])

query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.4300, 0.1500, 0.8900])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.5500, 0.8700, 0.6600])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.5700, 0.8500, 0.6400])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.2200, 0.5800, 0.3300])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.7700, 0.2500, 0.1000])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.0500, 0.8000, 0.5500])


tensor(1.4950)

In [38]:
attn_scores_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [7]:
normalized_attn_scores_2 = attn_scores_2 / attn_scores_2.sum()


print(attn_scores_2)
print(normalized_attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])


### Softmax Implementation for Attention Scores

In [8]:
def naive_softmax(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

In [9]:
attn_scores_2_native_softmax = naive_softmax(attn_scores_2)

print(attn_scores_2_native_softmax)
print(attn_scores_2_native_softmax.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [10]:
attn_scores_2_softmax_torch = torch.softmax(attn_scores_2, dim=0)

print(attn_scores_2_softmax_torch)
print(attn_scores_2_softmax_torch.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [32]:
context_vector_2 = torch.zeros(query.shape)

for i,x_i in enumerate(inputs):
    context_vector_2 += attn_scores_2_softmax_torch[i] * x_i

print(context_vector_2)

tensor([0.4419, 0.6515, 0.5683])


In [33]:
attn_scores=torch.empty(6,6)

In [48]:
attn_scores = inputs @ inputs.T

In [49]:
attn_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [50]:
attn_weights=torch.softmax(attn_scores,dim=-1)
attn_weights

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [ ]:
attn_weights[:,2]

tensor([0.1981, 0.2333, 0.2326, 0.2046, 0.1975, 0.2128])

In [63]:
context_matrix=attn_weights @ inputs

In [64]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [65]:
context_matrix

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

In [66]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])