In [1]:
import torch

#### Setence taken `Your journey starts with one step` 

In [2]:
inputs = torch.tensor([
    [ 0.43, 0.15,  0.89],
    [0.55,  0.87,  0.66],
    [ 0.57,  0.85, 0.64],
    [0.22, 0.58,  0.33],
    [ 0.77,  0.25, 0.10],
    [ 0.05,  0.80,  0.55]
], dtype=torch.float32)


In [3]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [4]:
query = inputs[1]  # Second 

attn_scores_2=torch.empty(inputs.shape[0])

In [5]:
for i,x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(query, x_i)

In [6]:
for i,x_i in enumerate(inputs):
    print("query:",query,'x_i',x_i)


torch.dot(query,inputs[1])

query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.4300, 0.1500, 0.8900])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.5500, 0.8700, 0.6600])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.5700, 0.8500, 0.6400])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.2200, 0.5800, 0.3300])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.7700, 0.2500, 0.1000])
query: tensor([0.5500, 0.8700, 0.6600]) x_i tensor([0.0500, 0.8000, 0.5500])


tensor(1.4950)

In [7]:
attn_scores_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [8]:
normalized_attn_scores_2 = attn_scores_2 / attn_scores_2.sum()


print(attn_scores_2)
print(normalized_attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])


### Softmax Implementation for Attention Scores

In [9]:
def naive_softmax(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

In [10]:
attn_scores_2_native_softmax = naive_softmax(attn_scores_2)

print(attn_scores_2_native_softmax)
print(attn_scores_2_native_softmax.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [11]:
attn_scores_2_softmax_torch = torch.softmax(attn_scores_2, dim=0)

print(attn_scores_2_softmax_torch)
print(attn_scores_2_softmax_torch.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [12]:
context_vector_2 = torch.zeros(query.shape)

for i,x_i in enumerate(inputs):
    context_vector_2 += attn_scores_2_softmax_torch[i] * x_i

print(context_vector_2)

tensor([0.4419, 0.6515, 0.5683])


In [13]:
attn_scores=torch.empty(6,6)

In [14]:
attn_scores = inputs @ inputs.T

In [15]:
inputs[0]

tensor([0.4300, 0.1500, 0.8900])

In [16]:
attn_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [17]:
attn_weights=torch.softmax(attn_scores,dim=-1)
attn_weights

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [18]:
attn_weights[:,2]

tensor([0.1981, 0.2333, 0.2326, 0.2046, 0.1975, 0.2128])

In [19]:
context_matrix=attn_weights @ inputs

In [20]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [21]:
context_matrix

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

In [22]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

## Self Attention With Traianble Weights

In [23]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [24]:
x_2=inputs[1]
d_in=inputs.shape[1]
d_out=2

In [25]:
torch.manual_seed(123)
W_query=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_key=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_value=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)

In [26]:
W_value

Parameter containing:
tensor([[0.0756, 0.1966],
        [0.3164, 0.4017],
        [0.1186, 0.8274]])

In [27]:
query=inputs@W_query
key=inputs@W_key
value=inputs@W_value

In [28]:
query

tensor([[0.2309, 1.0966],
        [0.4306, 1.4551],
        [0.4300, 1.4343],
        [0.2355, 0.7990],
        [0.2983, 0.6565],
        [0.2568, 1.0533]])

In [29]:
QK=query@key.T

In [30]:
QK

tensor([[0.9231, 1.3545, 1.3241, 0.7910, 0.4032, 1.1330],
        [1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440],
        [1.2544, 1.8284, 1.7877, 1.0654, 0.5508, 1.5238],
        [0.6973, 1.0167, 0.9941, 0.5925, 0.3061, 0.8475],
        [0.6114, 0.8819, 0.8626, 0.5121, 0.2707, 0.7307],
        [0.8995, 1.3165, 1.2871, 0.7682, 0.3937, 1.0996]])

In [31]:
d_k=key.shape[-1]
attn_weights_2=torch.softmax(QK/d_k**0.5,dim=-1)

In [32]:
V=inputs@W_value

In [33]:
final_attn_weights=attn_weights@V

In [34]:
final_attn_weights

tensor([[0.2897, 0.8043],
        [0.3069, 0.8188],
        [0.3063, 0.8173],
        [0.2972, 0.7936],
        [0.2848, 0.7650],
        [0.3043, 0.8105]])

In [35]:
import torch
import torch.nn as nn

class SelfAttention_v1(nn.Module):
    """
    A single-head self-attention mechanism.

    This module projects the input into query, key, and value vectors
    and then computes the attention weights and context vectors.
    """
    def __init__(self, d_in: int, d_out: int):
        """
        Initializes the SelfAttention_v1 module.

        Args:
            d_in (int): The dimensionality of the input feature vector.
            d_out (int): The dimensionality of the output query, key, and value vectors.
        """
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=False)
        self.W_key = nn.Linear(d_in, d_out, bias=False)
        self.W_value = nn.Linear(d_in, d_out, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Performs the forward pass of the self-attention mechanism.

        Args:
            x (torch.Tensor): The input tensor of shape (batch_size, num_tokens, d_in).

        Returns:
            torch.Tensor: The context vector of shape (batch_size, num_tokens, d_out).
        """
        # Project inputs into query, key, and value vectors
        queries = self.W_query(x)
        keys = self.W_key(x)
        values = self.W_value(x)

        # Compute attention scores
        # The last dimension of keys is d_out, so we transpose the last two dimensions
        attn_scores = queries @ keys.T

        # Scale scores and apply softmax to get weights
        # The scaling factor is the square root of the key dimension
        attn_weights = torch.softmax(attn_scores / self.d_out**0.5, dim=-1)

        # Compute the context vectors by weighting the values
        context_vec = attn_weights @ values
        return context_vec

In [36]:
torch.manual_seed(200)
attention_v1=SelfAttention_v1(d_in,d_out)

In [38]:
attention_v1(inputs)

tensor([[0.2789, 0.2778],
        [0.2744, 0.2670],
        [0.2743, 0.2666],
        [0.2742, 0.2664],
        [0.2712, 0.2592],
        [0.2758, 0.2704]], grad_fn=<MmBackward0>)

## Causal Attention

In [1]:
testing code 

SyntaxError: invalid syntax (2440392054.py, line 1)