In [1]:
import torch

#### Setence taken `Your journey starts with one step` 

In [ ]:
inputs = torch.tensor([
    [ 0.43, 0.15,  0.89],
    [0.55,  0.87,  0.66],
    [ 0.57,  0.85, 0.64],
    [0.22, 0.58,  0.33],
    [ 0.77,  0.25, 0.10],
    [ 0.05,  0.80,  0.55]
], dtype=torch.float32)


In [6]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [8]:
query = inputs[1]  # Second 

attn_scores_2=torch.empty(inputs.shape[0])

In [10]:
for i,x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(query, x_i)

In [11]:
attn_scores_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [14]:
normalized_attn_scores_2 = attn_scores_2 / attn_scores_2.sum()


print(attn_scores_2)
print(normalized_attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])


### Softmax Implementation for Attention Scores

In [15]:
def naive_softmax(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

In [16]:
attn_scores_2_native_softmax = naive_softmax(attn_scores_2)

print(attn_scores_2_native_softmax)
print(attn_scores_2_native_softmax.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [23]:
attn_scores_2_softmax_torch = torch.softmax(attn_scores_2, dim=0)

print(attn_scores_2_softmax_torch)
print(attn_scores_2_softmax_torch.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)
